[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "8evyL4dBzmnbHX7PFLY9H6nb7Ux6jxqNuk4n8z8K2xTX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/onggowahyudi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
